pipeline {
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: java-agent
    image: registry.access.redhat.com/ubi8/openjdk-17:latest
    command: ['cat']
    tty: true
    volumeMounts:
    - name: m2-cache
      mountPath: /home/jenkins/.m2
  - name: oc-client
    image: quay.io/openshift/origin-cli:latest
    command: ['cat']
    tty: true
  volumes:
  - name: m2-cache
    emptyDir: {}
"""
        }
    }

    environment {
        APP_NAME = "hello-microservice"
        // Force the absolute path to the project folder
        PROJECT_DIR = "Day5/CICD/hello-springboot-microservice"
    }

    stages {
        stage('Compile & Package') {
            steps {
                container('java-agent') {
                    dir("${env.PROJECT_DIR}") {
                        sh "mvn clean package -DskipTests"
                        // DEBUG: Verify the file is actually there
                        sh "ls -ld target" 
                    } 
                }
            }
        }

        stage('Build Custom Image') {
            steps {
                container('oc-client') {
                    script {
                        // Use the EXACT same variable to enter the folder
                        dir("${env.PROJECT_DIR}") {
                            openshift.withCluster() {
                                openshift.withProject() {
                                    if (!openshift.selector("bc", "${APP_NAME}-binary").exists()) {
                                        openshift.newBuild("--name=${APP_NAME}-binary", "--strategy=source", "--binary=true", "--image=registry.access.redhat.com/ubi8/openjdk-17:latest")
                                    }

                                    echo "Uploading target folder to OpenShift from: ${env.WORKSPACE}/${env.PROJECT_DIR}/target"
                                    
                                    // Trigger build - 'target/' is now relative to the PROJECT_DIR
                                    openshift.selector("bc", "${APP_NAME}-binary").startBuild("--from-dir=target/", "--wait")
                            
                                    def tag = "build-${env.BUILD_NUMBER}"
                                    openshift.tag("${APP_NAME}-binary:latest", "${APP_NAME}:${tag}")
                                }
                            }
                        }
                    }
                }
            }
        }

        stage('Deploy to OpenShift') {
            steps {
                container('oc-client') {
                    script {
                        openshift.withCluster() {
                            openshift.withProject() {
                                // Update this path to be absolute relative to workspace as well
                                dir("Day5/CICD/openshift") {
                                    sh "oc apply -f hello-deploy.yml"
                                    sh "oc apply -f hello-service.yml"
                                    sh "oc apply -f hello-route.yml"
                                }

                                def tag = "build-${env.BUILD_NUMBER}"
                                sh "oc set image deployment/${APP_NAME} ${APP_NAME}=image-registry.openshift-image-registry.svc:5000/\$(oc project -q)/${APP_NAME}:${tag}"
                                openshift.selector("deployment", APP_NAME).rollout().status()
                            }
                        }
                    }
                }
            }
        }
    }
}
